### ISSUE TITLE
MainPage.tsx의 Radio Button 입력

### ISSUE THREAD

**Issue by ytzka14** [Suyeon-Stom-Hwang/HCI_Project#25]
MainPage.tsx의 Radio Button 입력을 어디서 받는지 확인해 주실 수 있을까요? @Suyeon-Stom-Hwang

**Comment by Suyeon-Stom-Hwang** [comment]
https://github.com/Suyeon-Stom-Hwang/HCI_Project/pull/26
새로운 글 버튼을 눌렀을 때 onSubmit으로 한번에 받을 수 있게 만든 패치입니다.

라디오 버튼을 누를때마다 값을 받고 싶다면 RadioGroup 태그에 onValueChange property만 추가해줘도 됩니다.

```ts
            <RadioGroup defaultValue="comfortable" onValueChange={(value) => console.log(value)}>
```
